#==============国旗=================
import turtle as t
t.speed(0)
t.up()
t.goto(-375,250)
t.down()
t.color("red")
t.begin_fill()
for i in range(2):
    t.forward(750)
    t.right(90)
    t.forward(500)
    t.right(90)
t.end_fill()
t.up()
t.goto(-350,150)
t.down()
t.seth(0)
t.color("yellow")
t.begin_fill()
for i in range(5):
    t.forward(100)
    t.right(72)
    t.forward(100)
    t.right(144)
t.end_fill()
t.up()
t.goto(-200,200)
t.down()
t.seth(50)
t.color("yellow")
t.begin_fill()
for i in range(5):
    t.forward(30)
    t.right(72)
    t.forward(30)
    t.right(144)
t.end_fill()
t.up()
t.goto(-150,155)
t.down()
t.seth(20)
t.color("yellow")
t.begin_fill()
for i in range(5):
    t.forward(30)
    t.right(72)
    t.forward(30)
    t.right(144)
t.end_fill()
t.up()
t.goto(-150,95)
t.down()
t.seth(-5)
t.color("yellow")
t.begin_fill()
for i in range(5):
    t.forward(30)
    t.right(72)
    t.forward(30)
    t.right(144)
t.end_fill()
t.up()
t.goto(-200,50)
t.down()
t.seth(-30)
t.color("yellow")
t.begin_fill()
for i in range(5):
    t.forward(30)
    t.right(72)
    t.forward(30)
    t.right(144)
t.end_fill()
t.hideturtle()

#==============螺旋=================

yanse = ["red", "orange", "yellow", "green", "blue", "purple"]
t.penup()
t.goto(-375, 250)
t.seth(270)
t.pendown()
t.pensize(2)
for i in range(100):
    t.pencolor(yanse[i % 6])
    t.circle(3 + 2 * i, 25)

t.hideturtle()
t.done()
